SELECT  
        MIN(CASE WHEN OCCUPATION = 'Doctor'      THEN NAME ELSE NULL END),
        MIN(CASE WHEN OCCUPATION = 'Professor'   THEN NAME ELSE NULL END),
        MIN(CASE WHEN OCCUPATION = 'Singer'      THEN NAME ELSE NULL END),
        MIN(CASE WHEN OCCUPATION = 'Actor'       THEN NAME ELSE NULL END)
FROM 
      (SELECT OCCUPATION, NAME, 
      ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME) AS RANKING
      FROM OCCUPATIONS) AS T
GROUP BY 
    RANKING;
